[project]
name = "STX-VESTING-NFT"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/STX-vesting-NFT/STX-VESTING-NFT/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.stx-vesting-nft]
path = "contracts/stx-vesting-nft.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
